name: Build accessors

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  BUILD_TYPE: Release
  EMCC_VERSION: 3.1.56
  TAG_NUMBER: 1
  TAG_NAME: solver

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: mymindstorm/setup-emsdk@v14
      with:
        version: ${{env.EMCC_VERSION}}

    - uses: actions/checkout@v4

    - name: Configure
      run: emcmake cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}}

    - name: Build
      run: cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}}

    - name: Release
      uses: softprops/action-gh-release@v2
      with:
        tag_name: ${{env.TAG_NUMBER}}
        token : ${{ secrets.RELEASE_TOKEN }}
        files: |
          build/${{ env.TAG_NAME }}_${{env.TAG_NUMBER}}.wasm
          build/${{ env.TAG_NAME }}_${{env.TAG_NUMBER}}.js

